/* Generated by Owl Transpiler (Iteration 1) */
#include <stdint.h>
#include <stdio.h>
#include "owl_rt.h"

int main(void) {
    int32_t a = 1;
    float b = 3.14f;
    OwlString c = owl_str_from_cstr("hello world");
    uint8_t d = 1;
    owl_print_int(a);
    owl_print_float(b);
    owl_print_string(c);
    owl_print_bool(d);
    owl_str_free(&c);
    return 0;
}
